### DISCUSSION TITLE
Another way of editing default config, docker deployment

### DISCUSSION THREAD

**Discussion by g4xx** [excalith/excalith-start-page#54] [Ideas]
Hey again!

Currently hosting start-page via Docker/DockerHub has one fundamental issue - changes made through web UI will not persist if container is restarted/updated.

Building image locally with modified source kind of defeats the purpose of having images on DockerHub and adds a lot of overhead to building and modifying source.

Using docker volumes would be obvious answer but I am not sure how that would work with ability to edit from UI - this would require some research.

Best Regards!

**Comment by excalith** [comment]
Hey there! Actually all configs made through `config edit` stored in the local storage within your browser. Even if you stop or update the docker container, it will persist within your browser as long as you have the same IP and port. But I understand it can be frustrating depending on your network setup due to changes, or your browser clears all data after you quit.

However, if you are still having problems, you can use `config import <url>` command to import a remote json config to import your settings back. For more information regarding this, please check out [How To Customize](https://github.com/excalith/excalith-start-page/wiki/How-To-Customize) wiki page for different ways to customize.

For instance, to use my own config on my mobile devices, I use the web build and import my own configuration from my dotfiles repository with `config import https://raw.githubusercontent.com/excalith/.dotfiles/main/config/startpage/excalith-start-page.json` command.

I would suggest creating your own images if you forked this repository and made some source code changes besides the configuration. Otherwise, if the source code is the same, managing the configuration should persist on browsers. For this reason, I backed up my configuration on my dotfiles repository.

I am not sure if volumes are the best way for this. In order to do it, I think I need to serve it as an API to return configuration file from another container since it will be more of a server thing. 

Let me know what you think!

Cheers!

**Comment by g4xx** [comment]
Setting config with via URL is one way of solving that issue but in my opinion is not ideal. Accessing start-page from multiple devices (including mobile) becomes a hassle to setup. Using private browsing or cleaning cache is an issue too. Not to mention each new device will face same issue or that you'd have to have some reliable way of remembering that link. I'd rather have global configuration that simply works across devices.

Usually when setting up similar projects you'd go and use DNS server and reverse proxy to be able to access it through some domain like https://dashboard.home. This way you can easily access it through multiple devices and have exactly same setup without all the hassle of configuration each time you're accessing it from new device/OS/session.

I must say that I really like the project and in my eyes it would be a great Homarr, Homepage or Dashy alternative. I would like to make it work for me and I guess a lot of folks on /r/homelab would want that too (highly encourage you to advert project there). All those projects however offer some easy way of changing config and not worry too much about updates or container restarts.

**Comment by excalith** [comment]
Hey @g4xx, thanks for clarifying those in detail, I have a very basic home setup so I lacked the knowledge of good improvements. However, checking out those projects gave me a great vision! Also, I now that I see, I misinterpreted the idea behind volumes before. I will definetely look into this but as you mentioned earlier, I really need some time to research before starting refactoring the source code. 

I suppose the first thing I should do is to get rid of the browser local storage. It will definetely break hearts of the users who prefer using online preview version, but with a simplified docker setup phase (like compose you mentioned as well) it will be easier for everyone to get into the Docker world. This will definetely further improve the stability and usability of the app.

I will also try building for armv7 for my old rusty RPi2 to try things locally. This will take some time, but I will try to do my best!

Thanks so much again for lots of great suggestions!

**Reply by g4xx** [reply]
> I suppose the first thing I should do is to get rid of the browser local storage. It will definetely break hearts of the users who prefer using online preview version

Not sure if alienating your current audience would serve the project but that depends on how many users are actually using it.

I guess you could do both. If someone wants to use URL config feature / browser cache it is fine. I don't think that it _has_ to be one or the other but it would definitely add code complexity.

Glad I could help!

**Comment by excalith** [comment]
Hey again @g4xx!

I think I managed to seperate Docker and web-based configurations using a volume for settings to persist.

Now, while using Docker either `config edit` and `config import <url>` overrides the json file within that volume, completely omitting local browser storage, so you should be able to share the same configuration between devices. On the other hand, web-based version still utilizes local storage for storing settings. So, no hearts broken :D

I would be grateful if you could try out give me another feedback regarding this!
```yml
version: '3.8'

services:
  start-page:
    container_name: start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - data:/app/public/data

volumes:
  data:
    name: excalith-start-page
 ```
 
Cheers!

**Reply by g4xx** [reply]
Hey @excalith ! Thanks for such a quick response!

Unfortunately I run into some issues using that change.

```
Error: EACCES: permission denied, open '/app/public/data/settings.json'
    at Object.openSync (node:fs:596:3)
    at Object.writeFileSync (node:fs:2322:35)
    at P (/app/.next/server/pages/api/saveSettings.js:1:705)
    at /app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16566
    at /app/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /app/node_modules/next/dist/server/lib/trace/tracer.js:122:103 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/app/public/data/settings.json'
}
```

I don't think that is permission issue with docker host on my machine as I run this as root. I guess this has to do something within the container.

**Reply by excalith** [reply]
Bummer. This is kind of a "works on my machine" thing right now :D

Did you use `config edit` command or directly tried to change the `/app/public/data/settings.json` from portainer or docker term? Or did this happen when you launched the URL for the first time?

**Reply by g4xx** [reply]
I've used Portainer to deploy my container (I usually do) but it didn't really create settings.json in that folder since it cannot get access to it. Only thing I've changed to your docker-compose is the path in my system for the data folder which I pointed into my home directory (I always do it this way). I also tried creating settings.json myself but that didn't help either. I tried of course using config edit but the changes are not persisting even through a refresh now.

I've seen your changes and I see that you do set chmod 777 to data folder. Maybe chown should be there too? Sorry for being useless when it comes to Docker. I mostly use it for deployment rather than creating images.

**Reply by excalith** [reply]
Gotcha! Changing chmod and chown should indeed fix this issue, but comes with security problems where someone can execute code as well. While I was trying to write the settings.json through the `config edit` command, I realised I do not need that 777 at all, since the app has its own access to that file. Probably changing path to data folder required additional permissions such as public rwx. This might be the case where your settings file did not write and not readable. In your case, I did not consider changing path as you did, and will ask docker wizards for guidance how to do this properly.

By the way, you are not being useless. Instead, you are awesome! I do not have much homelab experience and learning both docker further and understanding how users use their own setups with your feedbacks! 

I hope docker community will guide me through this little obstacle. 

Cheers!

**Reply by excalith** [reply]
Hey @g4xx, thanks to Docker community I have learned that `chown` should be enough to support your case.

I have tried the latest `docker-volume-test` and changed the path into my desktop. Whenever I launched the URL, it created `settings.json` file where I can edit via any text editor without an issue (formerly I replicated your issue by changing the path)

Can you give it another try? I am pretty excited about this change!
```yml
version: '3.8'

services:
  start-page:
    container_name: start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - data:/app/public/data

volumes:
  data:
    name: excalith-start-page
```

This gave me an idea to symlink my dotfiles config for start page into the custom path we can make. I have to try this, but if I can manage to do so, it would be great!

**Reply by g4xx** [reply]
For some reason I still get the same error. Removed whole directory, repulled image and recreated container to make sure. Maybe this should be applied separately for each platform? Just guessing unfortunately :/

**Reply by excalith** [reply]
Unfortunately each platform uses the same Dockerfile since it is platform agnostic, so they all have the same `chown`. It seems like there is more to take into consideration regarding your use case. Haven't used portainer before, and I doubt it causing that issue. 

However, on my end, after removing everything I simply pulled latest test image and used compose file to start it.
Here is my test compose for bound mount
```yml
version: '3.8'

services:
  start-page:
    container_name: excalith-start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - "C:/Users/xxx/Desktop/data:/app/public/data"

volumes:
  data:
    name: excalith-start-page
```

It created an empty data folder on my desktop. When I launched the app, it created the settings.json file within it. I was able to change the json using text editor and via `config edit`. Both of them reflected the update. 

By any chance we might be doing something different?

**Reply by g4xx** [reply]
In my case when I run the app from Portainer it creates the folder that I assign it to but it doesn't create settings.json. When I enter UI and type config edit it Errors out at that moment.

For a second I thought that maybe path with double quotes was at fault but it works same regardless.

``` yml
version: '3.8'

services:
  start-page:
    container_name: excalith-start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    ports:
      - 6699:3000
    volumes:
      - /home/gaxx/projects/start-page/:/app/public/data

volumes:
  data:
    name: excalith-start-page
```

Here is my exact compose file - nothing really changed here except the port (irrelevant) and path (which is correct since I see folder created in that path)

**Reply by g4xx** [reply]
Ok, I dug a bit deeper. I've noticed that permissions on my system are exactly the same as for other containers but if I changed them to 777 on the data folder it settings.json appeared and it works!

**Reply by excalith** [reply]
Glad to hear 777 solved the issue you are having! At least we now know the problem. I will ask around if we can find a better solution besides setting 777. Otherwise, I will add it to the documentation as a side note.

Just to clarify, you used `chmod 777` on the data folder at `/home/gaxx/projects/start-page` right? No Dockerfile manipulations for testing?

Here is what I am trying to do as a best practice: https://serverfault.com/a/1006964
Here is an article about the security regarding volumes: https://redfoxsec.com/blog/insecure-volume-mounts-in-docker/

**Reply by g4xx** [reply]
Yes, I just did chmod 777 /home/gaxx/projects/start-page. This is bad but works for now. I guess you'll figure it out eventually :)

**Reply by g4xx** [reply]
A bit of an tangent but it would be nice to provide same mechanism for wallpapers since using local assets would always be faster in local network.

**Reply by excalith** [reply]
I guess I have found a better solution alternative to the chmod approach. This creates the container with root access. Still better than 777 it seems, and while trying to replicate your issue, I managed to run it without any issue this time. Still looking for a more elegant solution by avoiding both root and chmod and will let you know.

Here is the compose file with root just in case you wonder:
```yml
version: '3.8'

services:
  start-page:
    container_name: excalith-start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    user: 0:0
    ports:
      - 6699:3000
    volumes:
      - /home/gaxx/projects/start-page/:/app/public/data

volumes:
  data:
    name: excalith-start-page
```

To simply put the situation:
- The default compose file uses a named mount, which docker has all the access the app needs.
- Your compose file is a bind mount which requires additional permissions to be able to rwx. Adding root access seems to solve this issue.

If there is no workaround, I believe the best solution without enforcing anyone to have root access by default is to document both named and bind composes seperately like so:

> If you want to use bind mounts, you should have root access to container to be able to read and write the files.
> *[Compose file example with root here]*

Regarding the wallpaper, I am willing to do this. I have already exposed the assets folder, but having trouble showing the assets within while using named mounts. Will get back to it after solving this.

**Reply by excalith** [reply]
Hey again @g4xx!

I managed to seperate the data folder completely from the nextjs static folder hell. Now you should be able to use data folder like your own directory. You can add wallpapers, fetch image and favicon using either `config edit` and changing `settings.json`.

I have asked docker wizards around and they all agreed about one thing:
If a user does bind a mount to docker system, it should be his responsibility to give permissions. So, giving root access to compose file or setting your user uid and gid should work fine, better than chmod 777.

As a best practice, I only create the necessary `settings.json` within that data folder. Leaving rest to user to add files as they require.

With this, you should be able to add and use
- Custom themes within `themes` folder
- Custom images within `assets` folder

Here is your latest compose file updated with user root access using `user: 0:0`. 
```yml
version: '3.8'

services:
  start-page:
    container_name: excalith-start-page
    image: excalith/start-page:docker-volume-test
    restart: unless-stopped
    user: 0:0
    ports:
      - 6699:3000
    volumes:
      - /home/gaxx/projects/start-page/:/app/public/data

volumes:
  data:
    name: excalith-start-page
```

Please let me know what you think! If everything is in order, I will merge this huge update as `v3.1.0`. Hopefully, I will only need to update the documentation for all those changes :D

**Reply by g4xx** [reply]
I deleted start-page dir and re-pulled image again. The directory is _not_ being created at all now, so no way of saving settings.json. Is there a more direct way to contact you, it seems this kind of thing would be easier to discuss and live test instead of discussing here.

**Reply by excalith** [reply]
Agreed. This turned out to be more complex than it sounds, but I believe we can find a solution. 

Could you drop me a message from this link https://cancellek.com/contact We can discuss how we can do a live session from there

**Reply by rubinghv** [reply]
I just want to get back to this issue since I absolutely love the concept of this project and am very excited about customizing it. I know I could fork the project etc. but I think respecting a custom `settings.json` file correctly and importing that on startup when self hosting (through reverse proxy like @g4xx ) is definitely preferable. 

I tried binding the docker volume through `/app/public/data` but this is still not loaded correctly on startup. Before when binding to `app/data` it would just overwrite the `settings.json` file on startup so at least this isn't happening anymore.

Typically the way containers work is that on first docker container startup, it would auto create all the local specific files (including wallpapers, themes which I've seen discussed in other issues), in the bound docker volume. This way users have their own settings/assets that they can easily modify seperate from the app logic (which is containerized and can be upgraded easily). This makes it very easy to upgrade the underlying software without losing the customization (and is one of the advantages of docker). The docker container can then read the contents of the bound volume and would not need to recreate any asset/themes/settings.json as they would be present on the bound docker volume (after the initial creation or after the user has created their own custom versions).

So having said all that (and I'm just explaining in case you're not familiar), I am not sure why currently only the settings.json actually ends up mounted back in the docker volume, but not assets folder that is created inside the data folder. I'm guessing it has to do with permissions (as 50% of all issues are related to permissions 😃 ).

I think I'll play around with creating my own docker file and seeing if I can address this.

**Comment by Watenk** [comment]
Hi, When i bind the docker volume using this docker compose file:
``` 
start-page:
      container_name: exalith-start-page
      restart: unless-stopped
      user: 1000:1000
      ports:
          - 3001:3000
      image: excalith/start-page
      volumes:
          - /MyOwnFolder:/app/data
 ```
 it only generates the settings.json in MyOwnFolder and not the themes and assets folder. Is this intended?
